### ISSUE TITLE
Tricky queries UNKNOWN - unable to parse prometheus response

### ISSUE THREAD

**Issue by VictCM** [magenta-aps/check_prometheus_metric#12]
Hi, I have an issue when trying to run some tricky queries. The thing is that I am trying to use Icinga to check metrics on my services, where all of them are containers. If I configure simple queries as an "sum(up)" I got the info and I can create critical and warning notifications, but the problem comes when I configured a more complex query, working with some labels and GROUP BYs. I think that maybe it could be some character I need to escape, for not sure how ( I've tried a lot of options)

If I execute the query from the command itself I am getting response, but I do not if I set the command as a service.

## The query:
`scalar((sum(rate(container_cpu_usage_seconds_total{name=~".*grafana.*-grafana-.*"}[1m])) BY (instance, name, env) * 100))`

## Output on icinga web:
`UNKNOWN - unable to parse prometheus response`
or check didn't appear.

## Output on CLI:
```
/usr/lib/nagios/plugins/check_prometheus_metric.sh -H http://myprometheusinstance:port -c 5: -w 10: -n check_back_cpu -q 'scalar((sum(rate(container_cpu_usage_seconds_total{name=~".*grafana.*-grafana-.*"}[1m])) BY (instance, name, env) * 100))'

CRITICAL - check_grafana_cpu is 0.2051226219923568
```

```
object Service "check_grafana_cpu" {
    import "generic-service"
    host_name = "icinga2-magnet-pro"
        check_command = "check_prometheus_metric"
    command_endpoint = "icinga2-pro"
    vars.check_prometheus_metric_url = "myprometheusinstance:port"
    vars.check_prometheus_metric_query = "scalar((sum(rate(container_cpu_usage_seconds_total{name=~\".*grafana.*-grafana-.*\"}[1m]))BY(instance, name, env)*100))"
    vars.check_prometheus_metric_name = "grafana cpu"
    vars.check_prometheus_metric_warning = "60"
    vars.check_prometheus_metric_critical = "80"
}
```
Any help with this? Thanks a lot!

**Comment by Skeen** [comment]
That does look like an escaping issue!

My suggestion would be replacing the `check_prometheus_metric.sh` script with a script which just does `echo $@` and seeing how arguments differ from when you're calling it directly.

If you find the issue and how escaping is misbehaving please report back 😊

**Comment by VictCM** [comment]
I found what character is the one causing problems: **{** (and } ).

`scalar((sum(rate(container_cpu_usage_seconds_total\{name=~"grafana"\}[1m]))BY(instance, name, env)*100))`

I have tried to escape them that way but with no result. When the query has these characters I don't have any response from Icinga (new service is not applied and it didn't appear on Icinga web).

**Comment by VictCM** [comment]
Hello again, I found the error, It seems it was on my own configuration. I was using an ansible to configure and dynamically built the alarms and "{" was not correctly evaluated.

`- hosts: ec2
  become: true
  become_user: root
  gather_facts: True
  vars:
    first_cb: "{"
    second_cb: "}"
  roles:
    - role: ansible-icinga2-client
      [...]
      icinga2_checks:
        - name: check_grafana_cpu
          command: check_prometheus_metric
          extra_vars_command:
            - name: check_prometheus_metric_url
              value: "prometheus-master.magnet-master.admin.local:9090"
            - name: check_prometheus_metric_query
              value: "scalar(sum(rate(container_cpu_usage_seconds_total{{ first_cb }}name=~'.*grafana.*-grafana-master.*'{{ second_cb }}[1m]))BY(instance,name,env)*100)"
            - name: check_prometheus_metric_name
              value: "grafana cpu check"
            - name: check_prometheus_metric_warning
              value: "60"
            - name:  check_prometheus_metric_critical
              value: "80"`

Thanks!
