### ISSUE TITLE
preamble.bash / parse.bash / usage.bash : No such file or directory

### ISSUE THREAD

**Issue by picoroma** [magenta-aps/check_prometheus_metric#14]
I have a problem running the command on an UBUNTU 18.04
I'm using with ICINGA - But the error is even at OS level
I have copied these files:
preamble.bash
parse.bash
usage.bash
In the same folder with "check_prometheus_metric.sh".
The folder looks like:
![image](https://user-images.githubusercontent.com/23618664/172836810-c90d82fb-717a-484e-a789-4604deb84ff3.png)

/usr/lib/nagios/plugins/check_prometheus_metric/check_prometheus_metric.sh: line 29: preamble.bash: No such file or directory
/usr/lib/nagios/plugins/check_prometheus_metric/check_prometheus_metric.sh: line 30: parse.bash: No such file or directory
/usr/lib/nagios/plugins/check_prometheus_metric/check_prometheus_metric.sh: line 31: usage.bash: No such file or directory
/usr/lib/nagios/plugins/check_prometheus_metric/check_prometheus_metric.sh: line 68: is_float_or_interval: command not found
/usr/lib/nagios/plugins/check_prometheus_metric/check_prometheus_metric.sh: line 70: usage: command not found

**Comment by Skeen** [comment]
Hi, please use the script provided in releases, not the source files themselves.

**Comment by picoroma** [comment]
HI! 
where I can find the right file ?
Inthe the .zip file I downloaded  there is no "check_prometheus_metric.sh" other than into folder "src"...

**Comment by Skeen** [comment]
https://github.com/magenta-aps/check_prometheus_metric/releases/download/v0.0.6/check_prometheus_metric.sh

**Comment by Skeen** [comment]
In general on: https://github.com/magenta-aps/check_prometheus_metric/releases/latest
